#!/usr/bin/env bash 

# Delete .pyc files
cd ./$(git rev-parse --show-cdup)

TOTAL_PYC_FILES=$( find . -name "*.pyc" | wc -l | tr -d ' ' )
if [ $TOTAL_PYC_FILES -gt 0 ]; then
    find . -name "*.pyc" -delete
    printf "\e[00;31mDeleted $TOTAL_PYC_FILES .pyc files\e[00m\n"
fi
